// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/darp-operator/pkg/apis/okto/v1alpha1.Darp":       schema_pkg_apis_okto_v1alpha1_Darp(ref),
		"github.com/darp-operator/pkg/apis/okto/v1alpha1.DarpSpec":   schema_pkg_apis_okto_v1alpha1_DarpSpec(ref),
		"github.com/darp-operator/pkg/apis/okto/v1alpha1.DarpStatus": schema_pkg_apis_okto_v1alpha1_DarpStatus(ref),
	}
}

func schema_pkg_apis_okto_v1alpha1_Darp(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Darp is the Schema for the darps API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/darp-operator/pkg/apis/okto/v1alpha1.DarpSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/darp-operator/pkg/apis/okto/v1alpha1.DarpStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/darp-operator/pkg/apis/okto/v1alpha1.DarpSpec", "github.com/darp-operator/pkg/apis/okto/v1alpha1.DarpStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_okto_v1alpha1_DarpSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DarpSpec defines the desired state of Darp",
				Properties: map[string]spec.Schema{
					"size": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"rootCaSecret": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"serverCertsSecret": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"serverConfigMap": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"certsMountPath": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"size", "rootCaSecret", "serverCertsSecret", "serverConfigMap", "certsMountPath"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_okto_v1alpha1_DarpStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DarpStatus defines the observed state of Darp",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
