apiVersion: apps/v1
kind: Deployment
metadata:
  name: darp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: darp-operator
  template:
    metadata:
      labels:
        name: darp-operator
    spec:
      serviceAccountName: darp-operator
      containers:
        - name: darp-operator
          image: "docker.io/dimssss/darp-operator:0.1"
          command:
          - darp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "darp-operator"
